apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: much-todo
type: Opaque
data:
  MONGO_URI: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQG1vbmdvZGItc2VydmljZToyNzAxNy9tdWNoX3RvZG9fZGI/YXV0aFNvdXJjZT1hZG1pbg==
  JWT_SECRET_KEY: ODQzNyomXiQmVlJERSoqV0hpZDh3eXUwOGtqZC5mN3RnZGc3
